### ISSUE TITLE
error: "TypeError: forward() got an unexpected keyword argument 'masked_lm_labels'"

### ISSUE THREAD

**Issue by xuyifan-0731** [princeton-nlp/OptiPrompt#3]
i try to run the model by bash scripts/run_optiprompt.sh, but the model was not trainning and output this:
`
03/16/2022 15:53:28 - INFO - __main__ - Namespace(check_step=-1, common_vocab_filename='common_vocabs/common_vocab_cased.txt', dev_data='data/autoprompt_data/P1001/dev.jsonl', do_eval=True, do_shuffle=False, do_train=True, eval_batch_size=8, eval_per_epoch=3, init_manual_template=True, k=5, learning_rate=0.003, model_dir=None, model_name='bert-base-cased', num_epoch=10, num_vectors=5, output_dir='optiprompt-outputs/P1001', output_predictions=True, random_init='none', relation='P1001', relation_profile='relation_metainfo/LAMA_relations.jsonl', seed=6, test_data='data/LAMA-TREx/P1001.jsonl', train_batch_size=16, train_data='data/autoprompt_data/P1001/train.jsonl', warmup_proportion=0.1)
03/16/2022 15:53:28 - INFO - __main__ - # GPUs: 8
03/16/2022 15:53:28 - INFO - __main__ - Model: bert-base-cased
Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
03/16/2022 15:53:50 - INFO - models - Vocab size: 28996
Using eos_token, but it is not set yet.
03/16/2022 15:53:50 - INFO - __main__ - Original vocab size: 28996
03/16/2022 15:53:50 - INFO - __main__ - # vocab after adding new tokens: 29006
03/16/2022 15:53:50 - INFO - __main__ - Common vocab: common_vocabs/common_vocab_cased.txt, size: 21018
03/16/2022 15:53:51 - INFO - __main__ - Tie embeddings of tokens: ([V1], is)
03/16/2022 15:53:51 - INFO - __main__ - Tie embeddings of tokens: ([V2], a)
03/16/2022 15:53:51 - INFO - __main__ - Tie embeddings of tokens: ([V3], legal)
03/16/2022 15:53:51 - INFO - __main__ - Tie embeddings of tokens: ([V4], term)
03/16/2022 15:53:51 - INFO - __main__ - Tie embeddings of tokens: ([V5], in)
03/16/2022 15:53:51 - INFO - __main__ - Tie embeddings of tokens: ([V6], .)
03/16/2022 15:53:51 - INFO - __main__ - Template: [X] [V1] [V2] [V3] [V4] [V5] [Y] [V6]
03/16/2022 15:53:51 - INFO - __main__ - Train batches: 7
03/16/2022 15:53:51 - INFO - __main__ - Valid batches: 4
  0%|                                                                                                                        | 0/4 [00:00<?, ?it/s]03/16/2022 15:53:51 - INFO - models - Moving model to CUDA
  0%|                                                                                                                        | 0/4 [00:22<?, ?it/s]
Traceback (most recent call last):
  File "code/run_optiprompt.py", line 174, in <module>
    best_result, result_rel = evaluate(model, valid_samples_batches, valid_sentences_batches, filter_indices, index_list)
  File "/home/XuYifan/optiprompt/OptiPrompt/code/utils.py", line 110, in evaluate
    log_probs, cor_b, tot_b, pred_b, topk_preds, loss, common_vocab_loss = model.run_batch(sentences_b, samples_b, training=False, filter_indices=filter_indices, index_list=index_list, vocab_to_common_vocab=vocab_to_common_vocab)
  File "/home/XuYifan/optiprompt/OptiPrompt/code/models.py", line 355, in run_batch
    loss, logits = self.mlm_model(
  File "/home/XuYifan/anaconda3/envs/XDAI/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/XuYifan/anaconda3/envs/XDAI/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/XuYifan/anaconda3/envs/XDAI/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/XuYifan/anaconda3/envs/XDAI/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/XuYifan/anaconda3/envs/XDAI/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/XuYifan/anaconda3/envs/XDAI/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/XuYifan/anaconda3/envs/XDAI/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'masked_lm_labels'
`
how can I deal with this problem?
my info:
Linux  3.10.0-1160.25.1.el7.x86_64
python 3.8
torch    1.7.0  
torchaudio    0.8.0 
transformers    3.0.0

**Comment by xuyifan-0731** [comment]
i notice my torch and transformers version are wrong. but after i change them to torch==1.4.0 and transformers==3.0.2, there is a new error, and the training not successed:


3/16/2022 22:38:05 - INFO - transformers.modeling_utils - loading weights file https://cdn.huggingface.co/bert-base-cased-pytorch_model.bin from cache at /root/.cache/torch/transformers/d8f11f061e407be64c4d5d7867ee61d1465263e24085cfa26abf183fdc830569.3fadbea36527ae472139fe84cddaa65454d7429f12d543d80bfc3ad70de55ac2
03/16/2022 22:38:08 - WARNING - transformers.modeling_utils - Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
03/16/2022 22:38:08 - WARNING - transformers.modeling_utils - Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['cls.predictions.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
03/16/2022 22:38:08 - INFO - models - Vocab size: 28996
03/16/2022 22:38:08 - ERROR - transformers.tokenization_utils_base - Using eos_token, but it is not set yet.
03/16/2022 22:38:08 - INFO - __main__ - Original vocab size: 28996
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V1] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V2] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V3] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V4] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V5] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V6] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V7] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V8] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V9] to the vocabulary
03/16/2022 22:38:08 - INFO - transformers.tokenization_utils - Adding [V10] to the vocabulary
03/16/2022 22:38:09 - INFO - __main__ - # vocab after adding new tokens: 29006
03/16/2022 22:38:09 - INFO - __main__ - Common vocab: common_vocabs/common_vocab_cased.txt, size: 21018
03/16/2022 22:38:10 - INFO - __main__ - Tie embeddings of tokens: ([V1], is)
03/16/2022 22:38:10 - INFO - __main__ - Tie embeddings of tokens: ([V2], a)
03/16/2022 22:38:10 - INFO - __main__ - Tie embeddings of tokens: ([V3], by)
03/16/2022 22:38:10 - INFO - __main__ - Tie embeddings of tokens: ([V4], profession)
03/16/2022 22:38:10 - INFO - __main__ - Tie embeddings of tokens: ([V5], .)
03/16/2022 22:38:10 - INFO - __main__ - Template: [X] [V1] [V2] [Y] [V3] [V4] [V5]
03/16/2022 22:38:10 - INFO - __main__ - Train batches: 7
03/16/2022 22:38:10 - INFO - __main__ - Valid batches: 4
  0%|                                                                                                                        | 0/4 [00:00<?, ?it/s]03/16/2022 22:38:10 - INFO - models - Moving model to CUDA
/home/XuYifan/anaconda3/envs/opti/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
  0%|                                                                                                                        | 0/4 [00:19<?, ?it/s]
**Traceback (most recent call last):
  File "code/run_optiprompt.py", line 174, in <module>
    best_result, result_rel = evaluate(model, valid_samples_batches, valid_sentences_batches, filter_indices, index_list)
  File "/home/XuYifan/optiprompt/OptiPrompt/code/utils.py", line 133, in evaluate
    eval_loss += loss.item() * tot_b
ValueError: only one element tensors can be converted to Python scalars**
03/16/2022 22:38:31 - INFO - __main__ - Namespace(check_step=-1, common_vocab_filename='common_vocabs/common_vocab_cased.txt', dev_data='data/autoprompt_data/P108/dev.jsonl', do_eval=True, do_shuffle=False, do_train=True, eval_batch_size=8, eval_per_epoch=3, init_manual_template=True, k=5, learning_rate=0.003, model_dir=None, model_name='bert-base-cased', num_epoch=10, num_vectors=5, output_dir='optiprompt-outputs/P108', output_predictions=True, random_init='none', relation='P108', relation_profile='relation_metainfo/LAMA_relations.jsonl', seed=6, test_data='data/LAMA-TREx/P108.jsonl', train_batch_size=16, train_data='data/autoprompt_data/P108/train.jsonl', warmup_proportion=0.1)
03/16/2022 22:38:31 - INFO - __main__ - # GPUs: 8
03/16/2022 22:38:31 - INFO - __main__ - Model: bert-base-cased
03/16/2022 22:38:33 - INFO - transformers.configuration_utils - loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-config.json from cache at /root/.cache/torch/transformers/b945b69218e98b3e2c95acf911789741307dec43c698d35fad11c1ae28bda352.9da767be51e1327499df13488672789394e2ca38b877837e52618a67d7002391
03/16/2022 22:38:33 - INFO - transformers.configuration_utils - Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 28996
}

**Comment by a3616001** [comment]
Hi, could you try to run with only one GPU? You can do that by setting `CUDA_VISIBLE_DEVICES=0`.

**Comment by xuyifan-0731** [comment]
> 

I run it on single GPU and find that there is an error in code/utils line 133:
I change
`eval_loss += loss.item() * tot_b`
to
`eval_loss += loss.mean().item() * tot_b`
and then success
